package com.ot.springboot.aop.controller;

import com.ot.springboot.aop.service.AopService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/aop")
public class AopController {

    @Autowired
    private AopService service;


    @GetMapping("/hello/{msg}")
    public String hello(@PathVariable("msg") String msg) {
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9"); service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9"); service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9"); service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9"); service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9"); service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9"); service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9"); service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9"); service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9"); service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        service.hello1(msg+"1");
        service.hello2(msg+"2");
        service.hello3(msg+"3");
        service.hello4(msg+"4");
        service.hello5(msg+"5");
        service.hello6(msg+"6");
        service.hello7(msg+"7");
        service.hello8(msg+"8");
        service.hello9(msg+"9");
        return "success";
    }
}
