server:
  port: 8001
spring:
  datasource:
    master:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/clouddb01
      username: root
      password: root
    slave:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/clouddb02
      username: root
      password: root
  jta:
    atomikos:
      datasource:
        xa-data-source-class-name:
