spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092 #指定kafka server的地址，集群配多个，中间，逗号隔开
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      batch-size: 524288
      buffer-memory: 524288000
      retries: 5
    #      transaction-id-prefix: kafka-tx-

    listener:
      missing-topics-fatal: false
      # 设置与分区相同的并发数，否则其他消费者也无法拉取消息
      concurrency: 10
      ack-mode: manual
    consumer:
      #      enable-auto-commit: true
      #      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 10
server:
  port: 8500